# Generated by Django 2.2.8 on 2022-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.TextField(max_length=100)),
                ('Price', models.FloatField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Image_Link', models.TextField(max_length=100)),
            ],
        ),
    ]
